class_labels: list[str] = [
 'Electrical Works - Ceiling fan',
 'Electrical Works - Electrical panel',
 'Electrical Works - Lamp',
 'Electrical Works - Light fixture',
 'Electrical Works - Socket',
 'Electrical Works - Switch',
 'Electrical Works - Wiring',
 'Flooring - Carpet',
 'Flooring - Linoleum',
 'Flooring - Liquid screed',
 'Flooring - Vinyl flooring',
 'Painting - Ceiling',
 'Painting - Decorative painting',
 'Painting - Decorative plaster',
 'Painting - Door',
 'Painting - Molding',
 'Painting - Wall',
 'Painting - Wallpaper',
 'Painting - Window',
 'Painting - Window trim',
 'Plumbing Works - - Water heater',
 'Plumbing Works - Bathtub',
 'Plumbing Works - Drainage system',
 'Plumbing Works - Faucet',
 'Plumbing Works - Pipes',
 'Plumbing Works - Shower cabin',
 'Plumbing Works - Sink',
 'Plumbing Works - Siphon',
 'Plumbing Works - Tap',
 'Plumbing Works - Toilet',
 'Tiling - Kitchen backsplash tile',
 'Tiling - Mosaic',
 'Tiling - Tile'
]
